### ISSUE TITLE
Update valheim vanilla to 0.156.2

### ISSUE THREAD

**Issue by zedalaye** [adaliszk/valheim-server#33]
Hello,

Valheim Server as been updated to 0.156.2. Would it be possible to update the container ?

**Comment by adaliszk** [comment]
Yes, sorry for the delay. Just committed https://github.com/adaliszk/valheim-server/commit/58c81bac51fe1fd7159c321fdc7d9430577f8b11 to bump the version.

The images should be up to date via https://github.com/adaliszk/valheim-server/actions/runs/992042756
