### ISSUE TITLE
Update Valheim to 0.209.10

### ISSUE THREAD

**Issue by zedalaye** [adaliszk/valheim-server#39]
Hi,

Valheim 0.209.8, 0.209.9 and 0.209.10 have been released. Any plans to update this repo ?

Thank you :)

-- zedalaye

**Comment by zedalaye** [comment]
Solution proposed : https://github.com/adaliszk/valheim-server/pull/40

**Comment by adaliszk** [comment]
Moving this to #42

**Comment by adaliszk** [comment]
Looks like the actions run through and pushed the tags.
