### ISSUE TITLE
Update valheim and v+

### ISSUE THREAD

**Issue by Code-Slave** [adaliszk/valheim-server#51]
trying to run v+ with an existing world and getting 
i> Server> incompatible data version 29

i think  v+ need updating

**Comment by adaliszk** [comment]
Hey,

You are correct. I had neglected it for a while. I'll try to include a quick fix for this!

**Comment by adaliszk** [comment]
Bumped with ec2dd3dac8fb35ffc6a0dc2131418ee2d2c69cd8, 
Once the pipeline finishes the image should be available: https://github.com/adaliszk/valheim-server/actions/runs/3729603781

**Comment by adaliszk** [comment]
Images updated, and the server seems to be able to start nicely!
